# Generated by Django 3.2.6 on 2021-09-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_authors_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
